### ISSUE TITLE
sequelize-msnodesqlv8@0.2.6-beta.7  - Initialization issue

### ISSUE THREAD

**Issue by psivas** [ratanakvlun/sequelize-msnodesqlv8#11]
When I try to instantiate sequelize as given in example

const db = new Sequelize({
  dialect: 'mssql',
  dialectModulePath: 'sequelize-msnodesqlv8',
  dialectOptions: {
    driver: 'SQL Server Native Client 11.0',
    instanceName: 'xxxxxx',
    trustedConnection: true
  },
  host: 'localhost',
  database: 'xxxx'
});

I am getting error message TypeError: Sequelize is not a constructor. I am using Typescript version 2.5

**Comment by psivas** [comment]
I was able to resolve this by changing the initialization piece of code to be as below:

const sequelize = new Sequelize.Connection

**Comment by ratanakvlun** [comment]
That solution is working for you? I don't think Sequelize can be used that way.  What does your Typescript file look like?

**Comment by psivas** [comment]
You are correct it didn't work for me. My requirement is to use windows native authentication captured from client browser [Angular 4 SPA] to authenticate to SQL server. The app is Angular-cli using Typescript 2.5.  Please let me know if this is the right approach.

My Typescript is something like this:

var express = require('express');
//var sql = require('mssql');
var sql = require('mssql/msnodesqlv8');
const Sequelize = require('sequelize-msnodesqlv8');
var jpp = require('json-path-processor');
var router = express.Router();

const sequelize = new Sequelize.Connection({
  database: 'xxxdbnamexxxx',
  dialect: 'mssql',
  dialectModulePath: 'sequelize-msnodesqlv8',
  logging: false,
  dialectOptions: {
    driver: 'SQL Server Native Client 11.0',
    instanceName: 'xxxxservernamexxxx',
    trustedConnection: true
  }
});

router.get('/getColors', function (req, res) {

/*I am not sure how to use the Sequelize here*/
  });

**Comment by ratanakvlun** [comment]
Integrated security doesn't work with SPAs in a browser. It uses a native security token of the currently logged in Windows user where the database is being accessed. In the case of an SPA, there is no native security token that is meaningful to the server. You may want to look into LDAP or some other authentication scheme where the user must enter credentials.

**Comment by psivas** [comment]
Thank you that's what I thought - need to do SSPI route.
