### ISSUE TITLE
Update msnodesqlv8

### ISSUE THREAD

**Issue by mokkabonna** [ratanakvlun/sequelize-msnodesqlv8#12]
Currently 0.3.2 is in use, 0.5.4 is out and have significant performance improvements.

https://github.com/TimelordUK/node-sqlserver-v8/issues/67

**Comment by steveh-101** [comment]
Cannot get working with node versions > 8.3  - msnodesqlv8 supports up to v10 at present

**Comment by sagitsofan** [comment]
Hey,
Do you have plans for updating this package to the newest msnodesqlv8 0.6.6 ?
I am encounter errors when using with "sequelize" and trying to run using npm scripts:

"Error: None of the binaries loaded successfully. Is your node version either >= 0.12.7 or >= 4.2.x or >= 5.1.1 or >= 6.1.0"

    

const sequelize = new Sequelize({
            dialect: 'mssql',
            dialectModulePath: 'sequelize-msnodesqlv8',
            dialectOptions: {
                connectionString: "conn string",
                trustedConnection: true
            },
            pool: {
                max: 5,
                min: 0,
                acquire: 30000,
                idle: 10000
            },
            database: '',
            username: '',
            password: ''
        });


Thanx

**Comment by ratanakvlun** [comment]
0.2.6-beta.8 removes the version restriction. sequelize-msnodesqlv8 is no longer being maintained. It may or may not work with msnodesqlv8 > 0.3.2.
