### ISSUE TITLE
Issue installing in ubuntu

### ISSUE THREAD

**Issue by pvijaysimha** [ratanakvlun/sequelize-msnodesqlv8#13]
Does it not support Linux?

If I run

 `npm install --save sequelize-msnodesqlv8`

I'm getting 

`npm ERR! notsup Unsupported platform for msnodesqlv8@0.3.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
`

**Comment by ratanakvlun** [comment]
It does not. It uses native Windows binaries.
