### ISSUE TITLE
Trusted connection inside a Linux Vm

### ISSUE THREAD

**Issue by RodrigoRVieira** [ratanakvlun/sequelize-msnodesqlv8#14]
Hi!

Good job providing this package! Thank you.

By the way, do you know how to establish a trusted connection inside a Linux VM?

**Comment by ratanakvlun** [comment]
The trusted connection feature of this module relies on Windows drivers to access the Windows security API.

As a general Linux solution, I don't know. There may be Microsoft protocols that allow it, but I haven't really looked into it.
