### ISSUE TITLE
Upgrade to latest version of msnodesqlv8

### ISSUE THREAD

**Issue by danscrima** [ratanakvlun/sequelize-msnodesqlv8#7]
The latest version is 0.3.1 which apparently has support for node version 8.x.x which we are using. Thanks!

**Comment by ratanakvlun** [comment]
The latest version of sequelize-msnodesqlv8 (0.2.6-beta.3) has been updated to use msnodesqlv8 0.3.1.

Note: Since 0.2.17, msnodesqlv8 has changed its error handling and it may behave differently than expected with sequelize-msnodesqlv8.
